#!/usr/bin/env bash
set -euo pipefail

case "$1" in
  version)
    printf "Client 27.0.0\n"
    ;;
  info)
    printf "Docker Engine: ok\n"
    ;;
  system)
    exit 0
    ;;
  context)
    exit 0
    ;;
esac
exit 0

