#!/usr/bin/env bash
set -euo pipefail

query="${*: -1}"
case "$query" in
  *"select(.Default == true) | .Name"*)
    printf "podman-machine-default\n"
    ;;
  *"[.[] | select(.Default == true)] | length"*)
    printf "1\n"
    ;;
  *".Running"*)
    printf "true\n"
    ;;
  *".Starting"*)
    printf "false\n"
    ;;
  *".State // \"unknown\""*)
    printf "running\n"
    ;;
  *"length"*)
    printf "1\n"
    ;;
  *)
    cat
    ;;
esac

